[package]
name = "ferum-application-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ferum-domain = { path = "../../crates/ferum-domain" }
ferum-application = { path = "../../crates/ferum-application" }
ferum-test-support = { path = "../support" }

async-trait = { workspace = true }
chrono = { workspace = true }
mockall = { workspace = true }
rust_decimal = { workspace = true }
serde_json = { workspace = true }
slug = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
uuid = { workspace = true }
