[package]
name = "ferum-web-tests"
version = "0.1.0"
edition = "2021"

[features]
script_plugins = ["ferum-web/script_plugins"]
default = ["script_plugins"]

[dependencies]
ferum-web = { path = "../../crates/ferum-web" }
ferum-domain = { path = "../../crates/ferum-domain", features = ["axum"] }
ferum-application = { path = "../../crates/ferum-application" }
ferum-infrastructure = { path = "../../crates/ferum-infrastructure" }

axum = { workspace = true, features = ["macros"] }
tower = { workspace = true, features = ["util"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
serde_json = { workspace = true }
validator = { workspace = true }
uuid = { workspace = true }
tera = { workspace = true }
