[package]
name = "ferum-test-support"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ferum-domain = { path = "../../crates/ferum-domain" }
ferum-application = { path = "../../crates/ferum-application" }

async-trait = { workspace = true }
chrono = { workspace = true }
mockall = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
