[package]
name = "ferum-infrastructure-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ferum-domain = { path = "../../crates/ferum-domain" }
ferum-application = { path = "../../crates/ferum-application" }
ferum-infrastructure = { path = "../../crates/ferum-infrastructure" }
migration = { path = "../../migration" }

async-trait = { workspace = true }
bcrypt = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
zip = { workspace = true }
sea-orm = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
serde_json = { workspace = true }
uuid = { workspace = true }
