//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::PostPolicy;
use super::sea_orm_active_enums::ViewPolicy;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub parent_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub position: i32,
    pub view_policy: ViewPolicy,
    pub post_policy: PostPolicy,
    #[sea_orm(column_type = "Text", nullable)]
    pub color: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub created_by_id: Option<Uuid>,
    pub updated_by_id: Option<Uuid>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub categories: BelongsTo<Option<Entity>>,
    #[sea_orm(has_many)]
    pub daily_stats: HasMany<super::daily_stats::Entity>,
    #[sea_orm(has_many)]
    pub threads: HasMany<super::threads::Entity>,
    #[sea_orm(has_many)]
    pub user_muted_categories: HasMany<super::user_muted_categories::Entity>,
    #[sea_orm(has_many)]
    pub user_roles: HasMany<super::user_roles::Entity>,
    #[sea_orm(has_many)]
    pub user_watched_categories: HasMany<super::user_watched_categories::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "created_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_2: BelongsTo<Option<super::users::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "updated_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_1: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
