//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "daily_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_daily_stats_category")]
    pub date: Date,
    #[sea_orm(column_type = "Text", unique_key = "idx_daily_stats_category")]
    pub metric: String,
    pub value: i64,
    #[sea_orm(unique_key = "idx_daily_stats_category")]
    pub category_id: Option<Uuid>,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub categories: BelongsTo<Option<super::categories::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
