//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plugin_storage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub plugin_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub key: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub value: Json,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "plugin_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub plugins: BelongsTo<super::plugins::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
