//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::PluginStatus;
use super::sea_orm_active_enums::PluginTier;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plugins")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub version: String,
    pub tier: PluginTier,
    pub status: PluginStatus,
    #[sea_orm(column_type = "JsonBinary")]
    pub manifest: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub granted_capabilities: Json,
    #[sea_orm(column_type = "Text")]
    pub install_path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub db_schema_name: Option<String>,
    pub db_schema_version: i32,
    pub installed_by: Option<Uuid>,
    pub installed_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub activated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    pub restart_count: i32,
    pub circuit_open: bool,
    #[sea_orm(has_many)]
    pub plugin_hooks: HasMany<super::plugin_hooks::Entity>,
    #[sea_orm(has_many)]
    pub plugin_logs: HasMany<super::plugin_logs::Entity>,
    #[sea_orm(has_many)]
    pub plugin_storages: HasMany<super::plugin_storage::Entity>,
    #[sea_orm(has_many)]
    pub plugin_ui_slots: HasMany<super::plugin_ui_slots::Entity>,
    #[sea_orm(
        belongs_to,
        from = "installed_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
    #[sea_orm(has_many)]
    pub webhooks: HasMany<super::webhooks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
