//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plugin_hooks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub plugin_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub hook_name: String,
    pub priority: i32,
    pub is_active: bool,
    pub avg_ms: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "plugin_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub plugins: BelongsTo<super::plugins::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
