//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::PostStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub thread_id: Uuid,
    pub author_id: Uuid,
    pub parent_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub content_md: String,
    #[sea_orm(column_type = "Text")]
    pub content_html: String,
    pub status: PostStatus,
    pub is_deleted: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub deleted_by_id: Option<Uuid>,
    pub edited_at: Option<DateTimeWithTimeZone>,
    pub edited_by_id: Option<Uuid>,
    pub edit_count: i32,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub posts: BelongsTo<Option<Entity>>,
    #[sea_orm(has_many)]
    pub reactions: HasMany<super::reactions::Entity>,
    #[sea_orm(has_many)]
    pub reports: HasMany<super::reports::Entity>,
    #[sea_orm(
        belongs_to,
        from = "thread_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub threads: BelongsTo<super::threads::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users3",
        from = "author_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub users_3: BelongsTo<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "deleted_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_2: BelongsTo<Option<super::users::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "edited_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_1: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
