//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "product_rating_stats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_id: Uuid,
    pub review_count: i32,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))", nullable)]
    pub avg_overall: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))", nullable)]
    pub avg_durability: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))", nullable)]
    pub avg_materials: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))", nullable)]
    pub avg_comfort: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))", nullable)]
    pub avg_aesthetics: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((4, 2)))", nullable)]
    pub avg_value_for_money: Option<Decimal>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "product_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub products: BelongsTo<super::products::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
