//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "product_categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub parent_id: Option<Uuid>,
    pub position: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    pub match_keywords: Vec<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub product_categories: BelongsTo<Option<Entity>>,
    #[sea_orm(has_many)]
    pub products: HasMany<super::products::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
