//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "product_materials")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub material_id: Uuid,
    #[sea_orm(
        belongs_to,
        from = "material_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub materials: BelongsTo<super::materials::Entity>,
    #[sea_orm(
        belongs_to,
        from = "product_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub products: BelongsTo<super::products::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
