//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ProductStatus;
use super::sea_orm_active_enums::ProductType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub product_type: ProductType,
    pub status: ProductStatus,
    pub brand_id: Option<Uuid>,
    pub category_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub style: Option<String>,
    pub price_min: Option<i32>,
    pub price_max: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub dimensions: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub origin: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub primary_image_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description_md: Option<String>,
    pub created_by_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "brand_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub brands: BelongsTo<Option<super::brands::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub product_categories: BelongsTo<Option<super::product_categories::Entity>>,
    #[sea_orm(has_many)]
    pub product_medias: HasMany<super::product_media::Entity>,
    #[sea_orm(has_one)]
    pub product_rating_stats: HasOne<super::product_rating_stats::Entity>,
    #[sea_orm(has_many)]
    pub threads: HasMany<super::threads::Entity>,
    #[sea_orm(
        belongs_to,
        from = "created_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
    #[sea_orm(has_many, via = "product_materials")]
    pub materials: HasMany<super::materials::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
