//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ReportStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub reporter_id: Uuid,
    pub post_id: Option<Uuid>,
    pub thread_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub status: ReportStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub moderator_notes: Option<String>,
    pub resolved_by_id: Option<Uuid>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub target_deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "post_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub posts: BelongsTo<Option<super::posts::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "thread_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub threads: BelongsTo<Option<super::threads::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "reporter_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub users_2: BelongsTo<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "resolved_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_1: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
