//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "role_permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub permission_id: Uuid,
    #[sea_orm(
        belongs_to,
        from = "permission_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub permissions: BelongsTo<super::permissions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub roles: BelongsTo<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
