//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "notification_kind")]
pub enum NotificationKind {
    #[sea_orm(string_value = "reply")]
    Reply,
    #[sea_orm(string_value = "mention")]
    Mention,
    #[sea_orm(string_value = "reaction")]
    Reaction,
    #[sea_orm(string_value = "best_answer")]
    BestAnswer,
    #[sea_orm(string_value = "warn")]
    Warn,
    #[sea_orm(string_value = "system")]
    System,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "plugin_status")]
pub enum PluginStatus {
    #[sea_orm(string_value = "installing")]
    Installing,
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "error")]
    Error,
    #[sea_orm(string_value = "disabled")]
    Disabled,
    #[sea_orm(string_value = "uninstalling")]
    Uninstalling,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "plugin_tier")]
pub enum PluginTier {
    #[sea_orm(string_value = "manifest")]
    Manifest,
    #[sea_orm(string_value = "script")]
    Script,
    #[sea_orm(string_value = "service")]
    Service,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "post_policy")]
pub enum PostPolicy {
    #[sea_orm(string_value = "members")]
    Members,
    #[sea_orm(string_value = "trusted")]
    Trusted,
    #[sea_orm(string_value = "staff_only")]
    StaffOnly,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "moderated")]
    Moderated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "post_status")]
pub enum PostStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "published")]
    Published,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "product_status")]
pub enum ProductStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "archived")]
    Archived,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "product_type")]
pub enum ProductType {
    #[sea_orm(string_value = "furniture")]
    Furniture,
    #[sea_orm(string_value = "material")]
    Material,
    #[sea_orm(string_value = "room")]
    Room,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "reaction_kind")]
pub enum ReactionKind {
    #[sea_orm(string_value = "like")]
    Like,
    #[sea_orm(string_value = "helpful")]
    Helpful,
    #[sea_orm(string_value = "insightful")]
    Insightful,
    #[sea_orm(string_value = "funny")]
    Funny,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "report_status")]
pub enum ReportStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "resolved")]
    Resolved,
    #[sea_orm(string_value = "dismissed")]
    Dismissed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "thread_status")]
pub enum ThreadStatus {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "locked")]
    Locked,
    #[sea_orm(string_value = "deleted")]
    Deleted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "trust_level")]
pub enum TrustLevel {
    #[sea_orm(string_value = "new")]
    New,
    #[sea_orm(string_value = "basic")]
    Basic,
    #[sea_orm(string_value = "member")]
    Member,
    #[sea_orm(string_value = "regular")]
    Regular,
    #[sea_orm(string_value = "leader")]
    Leader,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "view_policy")]
pub enum ViewPolicy {
    #[sea_orm(string_value = "public")]
    Public,
    #[sea_orm(string_value = "members_only")]
    MembersOnly,
    #[sea_orm(string_value = "staff_only")]
    StaffOnly,
}
