//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stored_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub key: String,
    pub content_type: String,
    /// The bytes, when the database is the storage backend.
    ///
    /// NULL means the file lives in an external store (S3) and this row carries
    /// only its metadata and reference count. Rows predating that split always
    /// have their bytes here, so `/files/` keeps serving them.
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub data: Option<Vec<u8>>,
    pub size: i64,
    pub ref_count: i32,
    pub uploaded_by_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub thread_thumbnails: HasMany<super::thread_thumbnails::Entity>,
    #[sea_orm(has_many)]
    pub user_avatars: HasMany<super::user_avatars::Entity>,
    #[sea_orm(has_many)]
    pub user_covers: HasMany<super::user_covers::Entity>,
    #[sea_orm(
        belongs_to,
        from = "uploaded_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
