//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub color: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub created_by_id: Option<Uuid>,
    #[sea_orm(
        belongs_to,
        from = "created_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
    #[sea_orm(has_many, via = "thread_tags")]
    pub threads: HasMany<super::threads::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
