//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "thread_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub thread_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: Uuid,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tags: BelongsTo<super::tags::Entity>,
    #[sea_orm(
        belongs_to,
        from = "thread_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub threads: BelongsTo<super::threads::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
