//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ThreadStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "threads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub category_id: Uuid,
    #[sea_orm(unique_key = "uq_threads_product_author")]
    pub author_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    pub status: ThreadStatus,
    pub is_pinned: bool,
    pub is_solved: bool,
    pub best_answer_id: Option<Uuid>,
    pub view_count: i32,
    pub reply_count: i32,
    pub last_post_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub deleted_by_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary")]
    pub custom_fields: Json,
    #[sea_orm(unique_key = "uq_threads_product_author")]
    pub product_id: Option<Uuid>,
    #[sea_orm(has_many)]
    pub bookmarks: HasMany<super::bookmarks::Entity>,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub categories: BelongsTo<super::categories::Entity>,
    #[sea_orm(
        belongs_to,
        from = "best_answer_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub posts: BelongsTo<Option<super::posts::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "product_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub products: BelongsTo<Option<super::products::Entity>>,
    #[sea_orm(has_many)]
    pub reports: HasMany<super::reports::Entity>,
    #[sea_orm(has_one)]
    pub review_ratings: HasOne<super::review_ratings::Entity>,
    #[sea_orm(has_one)]
    pub thread_thumbnails: HasOne<super::thread_thumbnails::Entity>,
    #[sea_orm(has_many)]
    pub thread_view_dedups: HasMany<super::thread_view_dedup::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "author_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub users_2: BelongsTo<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "deleted_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_1: BelongsTo<Option<super::users::Entity>>,
    #[sea_orm(has_many, via = "thread_tags")]
    pub tags: HasMany<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
