//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_follows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_user_follows")]
    pub follower_id: Uuid,
    #[sea_orm(unique_key = "uq_user_follows")]
    pub followed_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "followed_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users_2: BelongsTo<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "follower_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users_1: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
