//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_user_roles_scoped")]
    pub user_id: Uuid,
    #[sea_orm(unique_key = "uq_user_roles_scoped")]
    pub role_id: Uuid,
    #[sea_orm(unique_key = "uq_user_roles_scoped")]
    pub category_id: Option<Uuid>,
    pub granted_by: Option<Uuid>,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub categories: BelongsTo<Option<super::categories::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub roles: BelongsTo<super::roles::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "granted_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users_2: BelongsTo<Option<super::users::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users_1: BelongsTo<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
