//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::TrustLevel;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    pub is_email_verified: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    pub trust_level: TrustLevel,
    pub trust_score: i32,
    pub post_count: i32,
    pub days_visited: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub bio: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub website: Option<String>,
    pub is_banned: bool,
    pub banned_until: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ban_reason: Option<String>,
    pub warn_count: i32,
    pub failed_login_count: i32,
    pub locked_until: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub audit_logs: HasMany<super::audit_logs::Entity>,
    #[sea_orm(has_many)]
    pub bookmarks: HasMany<super::bookmarks::Entity>,
    #[sea_orm(has_many)]
    pub brands: HasMany<super::brands::Entity>,
    #[sea_orm(has_many)]
    pub notifications: HasMany<super::notifications::Entity>,
    #[sea_orm(has_many)]
    pub plugins: HasMany<super::plugins::Entity>,
    #[sea_orm(has_many)]
    pub products: HasMany<super::products::Entity>,
    #[sea_orm(has_many)]
    pub reactions: HasMany<super::reactions::Entity>,
    #[sea_orm(has_many)]
    pub site_configs: HasMany<super::site_config::Entity>,
    #[sea_orm(has_many)]
    pub stored_files: HasMany<super::stored_files::Entity>,
    #[sea_orm(has_many)]
    pub tags: HasMany<super::tags::Entity>,
    #[sea_orm(has_one)]
    pub user_avatars: HasOne<super::user_avatars::Entity>,
    #[sea_orm(has_one)]
    pub user_covers: HasOne<super::user_covers::Entity>,
    #[sea_orm(has_many)]
    pub user_muted_categories: HasMany<super::user_muted_categories::Entity>,
    #[sea_orm(has_one)]
    pub user_preferences: HasOne<super::user_preferences::Entity>,
    #[sea_orm(has_many)]
    pub user_watched_categories: HasMany<super::user_watched_categories::Entity>,
    #[sea_orm(has_many)]
    pub webhooks: HasMany<super::webhooks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
