//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "webhooks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    pub events: Vec<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub secret: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub created_by_id: Option<Uuid>,
    pub last_triggered_at: Option<DateTimeWithTimeZone>,
    pub failure_count: i32,
    pub plugin_id: Option<Uuid>,
    #[sea_orm(
        belongs_to,
        from = "plugin_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub plugins: BelongsTo<Option<super::plugins::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "created_by_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
