[package]
name = "ferum-application"
version = "0.1.0"
edition = "2021"

[dependencies]
ferum-domain = { path = "../ferum-domain" }

ammonia = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
pulldown-cmark = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
slug = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
